services:
  webgoat:
    image: webgoat/webgoat:latest
    container_name: webgoat
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:9090:9090"
    restart: unless-stopped
